server:
  port: 80
#logging:
#  level:
#    cn.zzf.spring.cloud.order.service: debug

spring:
  application:
    name: cloud-consumeropenfeign-order

# Eureka Client
eureka:
  client:
    # 是否将自己注册到Eureka Server
    register-with-eureka: false
    # 是否从Eureka Server抓取已有的注册信息，单节点无所谓，集群必须配合Ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 全局配置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: FULL
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

