server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  devtools:
    restart:
      enabled: true

  # 数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_2020?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zzfroot1.
  sleuth:
    sampler:
      # 采样值，0到1之间，1表示全部采样
      probability: 1
  zipkin:
    base-url: http://localhost:9411/


# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: cn.zzf.spring.cloud.payment.entity

# Eureka Client
eureka:
  client:
    # 是否将自己注册到Eureka Server
    register-with-eureka: true
    # 是否从Eureka Server抓取已有的注册信息，单节点无所谓，集群必须配合Ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment01
    prefer-ip-address: true
    # client多少秒向服务器发送一次心跳（默认30）
    lease-renewal-interval-in-seconds: 1
    # server端收到最后一次心跳后的等待时间上限
    lease-expiration-duration-in-seconds: 2