server:
  port: 2002
debug: true

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_storage?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: zzfroot1.

seata:
  enabled: true
  # 该属性需要与前面config.txt文件中的service.vgroupMapping后的值保持一致
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP # 这个值未生效, 在nacos中依然为DEFAULT_GROUP, 待检查原因
  registry:
    type: nacos
    nacos:
      # seata 在nacos中的服务名
      application: seata-server
      serverAddr: 127.0.0.1:8848
      # 分组需和seate分组一致
      group: SEATA_GROUP
  service:
    #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
    vgroup-mapping:
      my_test_tx_group: default
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
    grouplist:
      default: 127.0.0.1:8091
    #      disable-global-transaction: false

  enable-auto-data-source-proxy: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
