server:
  port: 8006

spring:
  application:
    name: cloud-consul-payment

  cloud:
    consul:
      host: 192.168.1.101
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: 192.168.1.2